AWS_BUCKET_NAME='photobin'
AWS_ACCESS_KEY_ID='AKIAJQMGWK6N23M5MGKA'
AWS_SECRET_ACCESS_KEY='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'
TWITTER_KEY=''
TWITTER_SECRET=''
FACEBOOK_KEY=''
FACEBOOK_SECRET=''